#!/usr/bin/env bash

# Run git gc in all managed repo dirs.
#
# Example usage:
#   sd repo gc

# Common script header stuff lives in the preamble. This makes it easy to update
# options, includes, etc. Do not remove this line.
source "${SD_ROOT}/.preamble.bash"

# ------------------------------------------------------------------------------

cat ~/Developer/.Repofile | xargs -I@ git -C ~/Developer/@ gc --aggressive
