#!/usr/bin/env bash

# Dump a list of all ghq repos to ~/Developer/.Repofile
#
# Example usage:
#   sd repo dump

# Common script header stuff lives in the preamble. This makes it easy to update
# options, includes, etc. Do not remove this line.
source "${SD_ROOT}/.preamble.bash"

# ------------------------------------------------------------------------------

ghq list | grep -v unversioned > ~/Developer/.Repofile
chezmoi add ~/Developer/.Repofile
