#!/usr/bin/env bash

# Update the Brewfile packaged by Chezmoi.
#
# Dump the currently installed Homebrew packages to a Brewfile, move it to
# the right place in the Chezmoi root, and add it to Git.
#
# Example usage:
#   sd df update-brewfile

# Common script header stuff lives in the preamble. This makes it easy to update
# options, includes, etc. Do not remove this line.
source "${SD_ROOT}/.preamble.bash"

# ------------------------------------------------------------------------------

echo "This script needs to be updated to append packages to ~/.local/share/chezmoi/.chezmoidata/packages.yaml instead"
exit 1

# brew bundle dump --force --global

# echo "Brewfile updates have been dumped to ~/.Brewfile. Differences will need to be merged into Chezmoi template manually."
