#!/usr/bin/env bash

# Apply Chezmoi configuration to system.
#
# Example usage:
#   sd df apply

# Common script header stuff lives in the preamble. This makes it easy to update
# options, includes, etc. Do not remove this line.
source "${SD_ROOT}/.preamble.bash"

# ------------------------------------------------------------------------------

chezmoi apply
