#!/usr/bin/env bash

# Find differences between the system config and what Chezmoi says it should be.
#
# Example usage:
#   sd df diff

# Common script header stuff lives in the preamble. This makes it easy to update
# options, includes, etc. Do not remove this line.
source "${SD_ROOT}/.preamble.bash"

# ------------------------------------------------------------------------------

chezmoi diff
