#!/usr/bin/env bash

# Edit neovim config files.
#
# Alias: dn
#
# Example usage:
#   sd df edit-nvim
#   dn

# Common script header stuff lives in the preamble. This makes it easy to update
# options, includes, etc. Do not remove this line.
source "${SD_ROOT}/.preamble.bash"

# ------------------------------------------------------------------------------

pushd ~/.config/nvim
nvim .
popd
