#!/usr/bin/env bash

# Edit zsh config files.
#
# Alias: dz
#
# Example usage:
#   sd df edit-zsh
#   dz

# Common script header stuff lives in the preamble. This makes it easy to update
# options, includes, etc. Do not remove this line.
source "${SD_ROOT}/.preamble.bash"

# ------------------------------------------------------------------------------

pushd ~/.config/zsh
nvim .
popd
