#!/usr/bin/env bash

# Clone a repo with ghq and add it to the Repofile for tracking.
#
# Example usage:
#   sd repo get git@foo.bar:myrepo.git

# Common script header stuff lives in the preamble. This makes it easy to update
# options, includes, etc. Do not remove this line.
source "${SD_ROOT}/.preamble.bash"

# ------------------------------------------------------------------------------

ghq get $1
${SD_ROOT}/repo/dump
