#!/usr/bin/env bash

# Update all managed repos to their most recent version.
#
# Example usage:
#   sd repo update

# Common script header stuff lives in the preamble. This makes it easy to update
# options, includes, etc. Do not remove this line.
source "${SD_ROOT}/.preamble.bash"

# ------------------------------------------------------------------------------

cat ~/Code/.Repofile | ghq get --parallel --update
