#!/usr/bin/env bash

# Sync and index configured mail accounts.
#
# If the account option is omitted, all accounts will be synced. If the account
# is specified, only the specified account will be synced.
#
# Afterward, *all* mail will be indexed (regardless of the account that might
# have been specified).
#
# Available options:
#   -a, --account                   Specify sync for a single account. Optional.
#
# Example usage:
#   sd mail sync
#   sd mail sync -a myaccount
#   sd mail sync --account myaccount

# Common script header stuff lives in the preamble. This makes it easy to update
# options, includes, etc. Do not remove this line.
source "${SD_ROOT}/.preamble.bash"

# ------------------------------------------------------------------------------

require_program "mbsync"

cleanup() {
    trap - SIGINT SIGTERM ERR EXIT
    clear_lock "mail-sync"
}

parse_params() {
    account='all'

    while :; do
        case "${1-}" in
        -a | --account)
            account="${2-}"
            shift
            ;;
        -?*) format_error "Unknown option: $1" ;;
        *) break;;
        esac
        shift
    done
}

parse_params "$@"

# Ensure there's an internet connection.
if ! check_connection; then
    format_error "No internet connection available. Skipping sync."
fi

# Acquire a lock.
[ -e ~/.mail-sync.lock ] && format_error "Another sync is already running"
trap cleanup SIGINT SIGTERM ERR EXIT
acquire_lock "mail-sync"

# Send any queued email. || true so that it doesn't cause this script to exit if
# there isn't any queued mail to send.
sd mail send

# Sync mail accounts.
if [ "$account" = "all" ]; then
    mbsync --all --verbose
else
    mbsync --verbose "$account"
fi

# Index all messages.
sd mail index
