#!/usr/bin/env bash

# Provide a filesystem based cache for bash commands.
#
# If a command takes a while to run, you can prefix it with `sd cache` and the
# output will be written to disk. Next time you run the command prefixed with
# `sd cache`, you'll get the cached version from disk. The cache lifetime is
# hardcoded to three hours, but you can manually delete the cache by clearing
# the contents of ~/.cache/sdcache
#
# If you want to force invalidation of the cache, you can set the environment
# variable SDCACHE_FORCE_EXEC to "true"
#
# Alias: cache
#
# Example usage:
#   sd cache echo hello world
#   sd cache my_long_running_script.sh

# Common script header stuff lives in the preamble. This makes it easy to update
# options, includes, etc. Do not remove this line.
source "${SD_ROOT}/.preamble.bash"

# ------------------------------------------------------------------------------

cache "$@"
