#!/usr/bin/env bash

# Extract almost any kind of archive.
#
# This script can extract most kinds of archives that are commonly found in a
# Unix-like environment.
#
# Example usage:
#   sd extract filename.tar.gz
#   sd extract filename.zip
#   sd extract file.gz

# Common script header stuff lives in the preamble. This makes it easy to update
# options, includes, etc. Do not remove this line.
source "${SD_ROOT}/.preamble.bash"

# ------------------------------------------------------------------------------
#

if [ -f $1 ]; then
	case $1 in
	*.tar.bz2) tar -jxvf $1 ;;
	*.tar.gz) tar -zxvf $1 ;;
	*.bz2) bunzip2 $1 ;;
	*.gz) gunzip $1 ;;
	*.tar) tar -xvf $1 ;;
	*.tbz2) tar -jxvf $1 ;;
	*.tgz) tar -zxvf $1 ;;
	*.zip) unzip $1 ;;
	*.ZIP) unzip $1 ;;
	*.pax) cat $1 | pax -r ;;
	*.pax.Z) uncompress $1 --stdout | pax -r ;;
	*.rar) unrar x $1 ;;
	*.Z) uncompress $1 ;;
	*) echo "'$1' is not supported. Add it!" ;;
	esac
else
	format_error "$1 is not a valid file"
fi
