#!/usr/bin/env bash

# Add Yubikey to SSH agent.
#
# Adds a Yubikey certificate to the current SSH agent. If that fails,
# sometimes the SSH agent needs to be restarted before trying again (which
# will be done automatically by this script if needed).
#
# Example usage:
#   sd yk

# Common script header stuff lives in the preamble. This makes it easy to update
# options, includes, etc. Do not remove this line.
source "${SD_ROOT}/.preamble.bash"

# ------------------------------------------------------------------------------

launchctl stop com.homebrew.ssh-agent
sleep 1
launchctl start com.homebrew.ssh-agent
sleep 1
ssh-add -s $HOMEBREW_PREFIX/lib/opensc-pkcs11.so
