# espanso configuration file
matches:
  - trigger: "..shrug"
    replace: "¯\\_(ツ)_/¯"
  
  - trigger: "..tableflip"
    replace: "(╯°□°）╯︵ ┻━┻"

  - trigger: "..zl"
    replace: "https://www.digitaldeployment.com/cameron/zoom"

  - trigger: "..lipsum"
    replace: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis fermentum molestie. Vestibulum congue auctor nisi, eu ultrices lectus facilisis eu. Nulla molestie ornare massa, sed malesuada urna consequat sed. Curabitur a nibh blandit felis imperdiet interdum. Vivamus eu malesuada purus. Suspendisse in lacus non quam sagittis porttitor. In hac habitasse platea dictumst. Nullam suscipit nulla non tellus interdum faucibus. Ut eget mauris mi. Nam rhoncus quis massa sit amet placerat. Donec sollicitudin enim nec ex rutrum, in ornare arcu venenatis. Praesent consequat enim ante, et ornare eros pellentesque ut."

  - trigger: "..ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl https://icanhazip.com"
          trim: true

  - trigger: "..unixtime"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "date +%s"
          trim: true

  - trigger: "..zi"
    replace: |
      Cameron Eagans is inviting you to a scheduled Zoom meeting.

      Topic: Cameron Eagans' Personal Meeting Room

      Join Zoom Meeting
      https://zoom.us/j/9162381804

      Meeting ID: 916 238 1804

      One tap mobile
      +16699006833,,9162381804# US (San Jose)
      +16465588656,,9162381804# US (New York)

      Dial by your location
              +1 669 900 6833 US (San Jose)
              +1 646 558 8656 US (New York)
      Meeting ID: 916 238 1804
      Find your local number: https://zoom.us/u/abaDHdWvft
