# espanso configuration file
matches:
  - trigger: "..shrug"
    replace: "¯\\_(ツ)_/¯"
  
  - trigger: "..tableflip"
    replace: "(╯°□°）╯︵ ┻━┻"

  - trigger: "..ddzl"
    replace: "https://www.digitaldeployment.com/cameron/zoom"

  - trigger: "..a6zl"
    replace: "https://us06web.zoom.us/my/cweagans.a6"

  - trigger: "..lipsum"
    replace: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lobortis fermentum molestie. Vestibulum congue auctor nisi, eu ultrices lectus facilisis eu. Nulla molestie ornare massa, sed malesuada urna consequat sed. Curabitur a nibh blandit felis imperdiet interdum. Vivamus eu malesuada purus. Suspendisse in lacus non quam sagittis porttitor. In hac habitasse platea dictumst. Nullam suscipit nulla non tellus interdum faucibus. Ut eget mauris mi. Nam rhoncus quis massa sit amet placerat. Donec sollicitudin enim nec ex rutrum, in ornare arcu venenatis. Praesent consequat enim ante, et ornare eros pellentesque ut."

  - trigger: "..ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl https://icanhazip.com"
          trim: true

  - trigger: "..unixtime"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "date +%s"
          trim: true

  - trigger: "..ddzi"
    replace: |
      Cameron Eagans is inviting you to a scheduled Zoom meeting.

      Topic: Cameron Eagans' Personal Meeting Room

      Join Zoom Meeting
      https://zoom.us/j/9162381804

      Meeting ID: 916 238 1804

      One tap mobile
      +16699006833,,9162381804# US (San Jose)
      +16465588656,,9162381804# US (New York)

      Dial by your location
              +1 669 900 6833 US (San Jose)
              +1 646 558 8656 US (New York)
      Meeting ID: 916 238 1804
      Find your local number: https://zoom.us/u/abaDHdWvft

  - trigger: "..a6zi"
    replace: |
      Cameron Eagans is inviting you to a scheduled Zoom meeting.

      Topic: Cameron Eagans's Personal Meeting Room

      Join Zoom Meeting
      https://us06web.zoom.us/j/4893440049

      Meeting ID: 489 344 0049
      One tap mobile
      +12532158782,,4893440049# US (Tacoma)
      +13462487799,,4893440049# US (Houston)

      Dial by your location
              +1 253 215 8782 US (Tacoma)
              +1 346 248 7799 US (Houston)
              +1 669 900 6833 US (San Jose)
              +1 301 715 8592 US (Washington DC)
              +1 312 626 6799 US (Chicago)
              +1 929 436 2866 US (New York)
      Meeting ID: 489 344 0049
      Find your local number: https://us06web.zoom.us/u/khRMS3HHG


