#!/bin/bash

## Description: Open current project database in the default application for mysql and/or postgres urls.
## Usage: db
## Example: "ddev db"
## OSTypes: darwin

dbtype=${DDEV_DBIMAGE%:*}
driver=mysql
if [[ $dbtype == "postgres" ]]; then
    driver=$dbtype
fi

set -x
query="${driver}://db:db@127.0.0.1:${DDEV_HOST_DB_PORT}/db"
open "$query"
