#!/usr/bin/env bash

# Prerequisites:
#   - Install yadm and git via pacman
#   - Install yay

# Install system level deps
echo " -> Ensuring that system dependencies are installed."
~/.yadm/scripts/install-system-deps.sh

# Set default shell to zsh.
echo " -> Setting default shell"
~/.yadm/scripts/zsh-default-shell.sh

# Install vigor
echo " -> Ensuring that Vigor is installed."
~/.yadm/scripts/vim-vigor.sh

# Set up the yadm update alias.
echo " -> Creating yadm update alias."
yadm gitconfig --local alias.update '!yadm pull && yadm decrypt && yadm bootstrap'

echo " -> Done."
