palette = "catppuccin_mocha"

format = """
$username\
$hostname\
$directory\
$line_break\
$character"""

right_format = """
$cmd_duration\
$git_status\
$git_branch"""

continuation_prompt = "▶▶ "

[directory]
style = "blue"
truncate_to_repo = false

[character]
success_symbol = "[❯](green bold)"
error_symbol = "[❯](red bold)"
vimcmd_symbol = "[❮](green bold)"

[git_branch]
symbol = " "
format = " [$symbol$branch]($style)"
style = "bright-black"

[git_status]
format = " [$ahead_behind]($style)"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
